version: 2.1


jobs:
  crypto-price:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: "Check Python version"
          command: python --version
      - run:
          name: "Install requirements"
          command: pip install -r requirements.txt
      - run:
          name: "Start the program"
          command: python start.py


workflows:
  commit:
    jobs:
      - crypto-price

  regular:
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - crypto-price
