version: 2.1


jobs:
  crypto-price:
    docker:
      - image: cimg/python:3.11.2
    steps:
      - checkout
      - run:
          name: "Check Python version"
          command: python --version
      - run:
          name: "Install requirements"
          command: pip install -r requirements.txt
      - run:
          name: "Start the program"
          command: python start.py


workflows:
  collect-price:
    jobs:
      - crypto-price
